export interface CI {
  //Login constant
  LOGIN_LOADING: string;
  LOGIN_SUCCESS: string;
  LOGIN_FAIL: string;
  LOGOUT: string;
  //Navigation menu List
  CREATE_MENU: string;
  SEARCH_LOADING: string;
  SEARCH_DISHES_SUCCESS: string;
  SEARCH_DISHES_FAIL: string;
  //menuDishes
  ADD_DISH_TO_MENU: string;
  DELETE_DISH_OF_MENU: string;
  SELECT_DISH_TO_MENU: string;
  COUNT_DISHES_TYPES: string;
  SHOW_DISH_DETAILS: string;
  EDIT_MENU_NAME: string;
  DEL_MENU_NAME: string;
}

const C: CI = {
  //Login constant
  LOGIN_LOADING: 'LOGIN_LOADING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  //Navigation menu List
  CREATE_MENU: 'CREATE_MENU',
  EDIT_MENU_NAME: 'EDIT_MENU_NAME',
  DEL_MENU_NAME: 'DEL_MENU_NAME',
  //search dishes
  SEARCH_LOADING: 'SEARCH_LOADING',
  SEARCH_DISHES_SUCCESS: 'SEARCH_DISHES_SUCCESS',
  SEARCH_DISHES_FAIL: 'SEARCH_DISHES_FAIL',
  //menuDishes
  ADD_DISH_TO_MENU: 'ADD_DISH_TO_MENU',
  DELETE_DISH_OF_MENU: 'DELETE_DISH_OF_MENU',
  SELECT_DISH_TO_MENU: 'SELECT_DISH_TO_MENU',
  COUNT_DISHES_TYPES: 'COUNT_DISHES_TYPES',
  //DishDetails
  SHOW_DISH_DETAILS: 'SHOW_DISH_DETAILS',
};

export default C;
